name: OCI A1 Provisioner

on:
  push:
    branches:
      - main

  schedule:
    - cron: "7,15,22,37,45,52 * * * *"

  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install SDK Requirements
        run: pip install -r requirements.txt

      - name: Provision OCI A1 Instance
        env:
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_PUBLIC_SSH_KEY: ${{ secrets.OCI_PUBLIC_SSH_KEY }}

        run: python "Ampere 24 ram 4 cpu/bot.py"
